### ISSUE TITLE
Web Notifications 

### ISSUE THREAD

**Issue by nickl-** [needim/noty#172]
Any plans on implementing Desktop Notification otherwise referred to as the Notification API or the [W3C Web Notifications specification](http://www.w3.org/TR/notifications/)

If yes what will it take to see this done this year still?

**Comment by rohinrohin** [comment]
Hey @needim, are you looking for someone to help you in doing this still? Let me know.

**Comment by needim** [comment]
Hi @rohinrohin, that would be good 👍

**Comment by needim** [comment]
Hi @rohinrohin, I created a branch named **push5**. Currently it is working (asking permissions, showing notifications, callbacks are working, registering service worker is ok) but I guess I have some issues with service worker support. Maybe it is related with manifest.json but I'm not totally sure.

If you want to help, you are welcome :)

**Comment by needim** [comment]
Finally we have some support in v3.1.0-beta, you can find details at http://ned.im/noty/web-push.html
