### ISSUE TITLE
bootstrap Theme not working

### ISSUE THREAD

**Issue by pakistanihaider** [needim/noty#215]
ok i updated,. 
theme: 'bootstrapTheme'
i dont get any errors but the theme dont work.. i mean i dont get any sucess or error message. 
I defined like this.

```
                            noty({
                                text: data[1],
                                type: data[2],
                                theme: 'bootstrapTheme',
                                closeWith: ['click']
                            });
```

it works if it is defaultTheme. but no message shown if i change themename.

**Comment by alvarotrigo** [comment]
This issue should be opened again...

**Comment by leopittoni** [comment]
same problem for me.

**Comment by emitrohin** [comment]
bootstap 3 list-group-item-* are not working

**Comment by needim** [comment]
in v3 there are css based bootstrap-v3 & bootstrap-v4 themes. JS themes are deprecated in v3.
But I will create a wrapper soon, for full support for bootstrap
