### ISSUE TITLE
timeout units not documented

### ISSUE THREAD

**Issue by aspiers** [needim/noty#240]
It seems that the `timeout` value must be in milliseconds, but this is not documented anywhere.  I initially tried setting it to `5`, and it never timed out.  That sounds like a bug to me - it should presumably vanish almost instantly?

**Comment by argunner** [comment]
@aspiers Same happend to me <b> timeout:delay(in milliseconds) </b> worked for me https://github.com/needim/noty/issues/246

**Comment by siddharthbhagwan** [comment]
Seems to work for me. Below 500 it all seems to work the same though, i.e, minimum time required to open and close without staying.

**Comment by needim** [comment]
info added.
