### ISSUE TITLE
Timeout with buttons?

### ISSUE THREAD

**Issue by kingy68** [needim/noty#244]
Hey,

Just wondering if it is possible to use the timeout option, if the noty has buttons?

I'm setting timeout to false in my defaults, then trying to create some noty's with buttons and overriding the timeout to 180*1000. I'm finding that I cant override the default timeout if I also set buttons within that noty. As soon as I remove the buttons I can override the timeout fine.

Is this expected?

Cheers

**Comment by allanlaal** [comment]
I would love to be able to set multiple criteria for closing notys

**Comment by needim** [comment]
same as #247
