### ISSUE TITLE
When loaded as an AMD module nothing is exported

### ISSUE THREAD

**Issue by sergiopereiraTT** [needim/noty#245]
Wouldn't it be intuitive for someone to use noty like this?

```javascript
//my module
define(['noty'], function(noty){
    var n = noty({  /* options */  });
});
```

This doesn't currently work (`noty` is `undefined`) because noty does not return or export anything from its factory function. I think this can be easily fixed by adding `return window.noty;` at the end of the factory function. 

Could we do that? Or was that omitted on purpose?

**Comment by LoicMahieu** [comment]
Fixed by #243
