### ISSUE TITLE
How Do i Set Closing Delay ?

### ISSUE THREAD

**Issue by flouthoc** [needim/noty#246]
When i set <b>timeout:true</b> is closes as soon as it appears in an instant.
When i set <b> timeout:false </b> or i do nothing it remains sticky

**Comment by argunner** [comment]
Oh Solved it <b> timeout:delay </b>

**Comment by cdl** [comment]
Curious as to how you got the timeout setting to work? Invoking a notification and setting the timeout option doesn't seem to work. See the example below:

```js
var n = noty({
	text: 'This is a test notification!',
	timeout: 1500,
	animation: {
		open: 'animated fadeInDown',
		close: 'animated fadeOutUp'
	}
});	
```

Tried out the above code and the notification stays static until you click to close it - as if the notification's `timeout` option isn't actually getting assigned to the given value and stays as `false`.

**Comment by cdl** [comment]
Fixed it by reverting from jQuery 2.x to jQuery 1.x. I'll work on a PR that fixes this for jQuery 2.x, but in the meantime, those experiencing this issue should look into using a 1.x version of jQuery.

**Comment by JoeAlamo** [comment]
@cdl Did you ever get a fix for this on jQuery 2.x?

**Comment by dschallert** [comment]
I'm also looking for a fix for JQuery 2.x..

**Comment by SweetLouHD** [comment]
Is timeout still broken?

**Comment by schallertd** [comment]
Haven't used the plugin for a while, will check my codebase later.  I think i've solved it with some workaround last year.

**Comment by SweetLouHD** [comment]
ok thanks. this would be great to get working with timeout.

**Comment by Fishthedj** [comment]
I am using it like this 
```javascript
           noty({
                text: 'Successfully added.',
                type: 'success',
                theme: 'relax',
                layout: 'center',
                timeout: 2000,
                animation: {
                    open: 'animated fadeInUp',
                    close: 'animated fadeOutUp'
                }
            });
```
with jQuery 3.1.0 and it works for me.

**Comment by SweetLouHD** [comment]
@Fishthedj thanks I guess my timeout was too small? I figured it was the time after the animation. It must be the time including the animation.

**Comment by Fishthedj** [comment]
@SweetLouHD I remember that I had problem with small timeout times (small ~ 500ms) So it seems that the timout starts when the open animation starts and must be long enough to let the open animation finish.

_Note: This is just my assumption. I haven't checked any of it in code._

**Comment by flouthoc** [comment]
Should i close this issue or what ? my problem is already solved but people look active here what should i do ?

**Comment by Fishthedj** [comment]
@flouthoc I would close it because the reported problem is not a code problem, only problem in documentation and you created another issue for that. So this one can be closed I think.
