### ISSUE TITLE
Unableto perform timeout when there are buttons in noty

### ISSUE THREAD

**Issue by flouthoc** [needim/noty#247]
timeout call doest not work when there are buttons in noty

**Comment by bkwdesign** [comment]
i've had to hack my noty.js (around line 66 in this current version) to also overcome this. 
Here's [another person talking about it on SO](http://stackoverflow.com/a/18404611/1520850)

**Comment by abhisek-sinha** [comment]
I understand that generally with an Ok/Cancel scenario, there is no point of having time out. 

In my case, I am trying to  give my users an ability to pin the message using a pin button. But as soon as I define a button to my noty object, the code sets the timeout to be false.
It would have been very helpful had there been any customization hook to control the timeout property even if there are buttons.

**Comment by rockerest** [comment]
+1 on this.

**Comment by allanlaal** [comment]
I would love to be able to set multiple criteria for closing notys

**Comment by flouthoc** [comment]
I did it by small tweak in noty source , @needim if you are not currently working on this issue can i create a PR ? otherwise i'll wait for your fix
