### ISSUE TITLE
Compatiblity browser

### ISSUE THREAD

**Issue by usb248** [needim/noty#252]
Euhm, very beautiful animation with animate.css but i haven't see any solution for IE browser <= 9, it's annoying ... 

Have you a solution or a solution to come ? Just if browser doesn't support CSS3 animation, simply use hide or show jquery function rather than something that doesn't work ...

(sorry for my bad english, i'm french :S )

**Comment by tengiz-borisoff** [comment]
Have that problem too... Just delivered a solution, but have not tested in IE compatibility mode.
Big fail on my part. Any suggestions? ... The top right noty seems to show on your site in compatibility mode  http://ned.im/noty/  .

**Comment by needim** [comment]
Related with #227

**Comment by usb248** [comment]
Euhm, other plugin add css property display:none juste after at the end of the css3 animation (to hide()) and display:block (to show()) at the same moment.

Or, check if the browser support CSS3 animation (with Modernizr for example) and change animation option acoording to this ...

When i set IE9 with emulator of IE browser, IE crash completely... and in local, noty appear but it's all... we can't hide noty :(.
