### ISSUE TITLE
Noty doesn't support IE6-IE9??

### ISSUE THREAD

**Issue by elkan1788** [needim/noty#253]
Hello, I'm a Chinese developer. One day I found your product on github. I just try it! But it doesn't work in IE8 , Why?? It's no errors in brower, I really had not way, I hope you can help me, Thank you.

**Comment by TrySound** [comment]
Hi. I think you need to use jquery 1.* legacy version for ie support

**Comment by teanoon** [comment]
ie8+ works fine in my case until i use animate.css for open & close animation.
so simply use jquery animation instead.
