### ISSUE TITLE
can't close / dismiss noty

### ISSUE THREAD

**Issue by alpertayfun** [needim/noty#255]
if I run just like that but I can't close / dismiss noty.. Is that bug or something ?

var noty_tip = noty({
        layout: 'topCenter',
        type: 'warning',
        theme: 'relax',
        text: 'Your post has been sent.',
        dismissQueue: true,
        force: true,
        animation: {
            open: 'animated flipInX', // Animate.css class names
            close: 'animated flipOutX', // Animate.css class names
        },
    });

$.noty.closeAll();

**Comment by alpertayfun** [comment]
i apologize for that. I fix it and learn it : )

But why $.not.closeAll(); event not working with timeout deal js ? I really want to learn it. Thank you.

    noty({
        layout: 'topCenter',
        type: 'warning',
        theme: 'relax',
        text: 'Your post has been sent.',
        timeout  : 2000,
        animation: {
            open: 'animated flipInX', // Animate.css class names
            close: 'animated flipOutX', // Animate.css class names
        }
    });

**Comment by dustinbolton** [comment]
Can't close noty with clicks nor timeout feature. Using with animate.css.  Even the most basic examples using defaults or overriding them to enable click closing both fail to allow noty to be closed.
