### ISSUE TITLE
Noty count is reached early when li elements are used in the message

### ISSUE THREAD

**Issue by who-stow** [needim/noty#256]
Multiple noty messages can be configured to be displayed using the __maxVisible__ property, but the limit can be reached early if HTML *li* elements are used within the noty message. The *__render__* function of the __notyRenderer__ compares the __maxVisible__ parameter with the number of *li* elements found in the noty container. When a user puts HTML into the message and uses *li* elements the count is actually including those *li* elements that the user message contains.

```javascript
    $.notyRenderer.render = function() {

        var instance = $.noty.queue[0];

        if($.type(instance) === 'object') {
            if(instance.options.dismissQueue) {
                if(instance.options.maxVisible > 0) {
                    //-------- This comparison should be more restricted in some way --------
                    if($(instance.options.layout.container.selector + ' li').length < instance.options.maxVisible) {
                        $.notyRenderer.show($.noty.queue.shift());
                    }
                    else {

                    }
                }
                else {
                    $.notyRenderer.show($.noty.queue.shift());
                }
            }
            else {
                if($.noty.ontap) {
                    $.notyRenderer.show($.noty.queue.shift());
                    $.noty.ontap = false;
                }
            }
        }
        else {
            $.noty.ontap = true; // Queue is over
        }

    };
```

A simple solution could be to add a class to the *li* elements that are noty specific and add the class to the selector above. Although the same issue could still happen, it's at least a lot less likely and pretty easily avoidable.

**Comment by siddharthbhagwan** [comment]
Merged! You can close this now :)
