### ISSUE TITLE
ES6 require('noty') doesn't work

### ISSUE THREAD

**Issue by max-mykhailenko** [needim/noty#257]
Try use noty, but get this error

`var Noty = require('noty/js');`

result 
```
ERROR in ./source/js/configs/app.js
Module not found: Error: Cannot resolve module 'noty' in /.../source/js/configs
 @ ./source/js/configs/app.js 5:11-29
```

**Comment by SleepWalker** [comment]
Do you mean commonJS? Because ES6 modules have another API.

I think, I have the same issue. The problem is that npm downloads package with wrong `package.json`. There is no "main" entry. You can temporary fix this issue by putting the following line manualy in your `node_modules/noty/package.json` file:

```json
  "main": "js/noty/packaged/jquery.noty.packaged.js",
```

**Comment by max-mykhailenko** [comment]
Now I just added full path to noty in my require
`require('noty/js/noty/packaged/jquery.noty.packaged.js');`

**Comment by AKurilin** [comment]
Just ran into this issue myself with browserify, thanks for the workaround.

**Comment by SleepWalker** [comment]
with webpack there is another option to setup an alias, so you won't need to change something in package and will still have `require('noty')` syntax. For browserify there is plugins to support aliases too.

**Comment by doublerebel** [comment]
:+1: for publishing latest version that has `main:` in `package.json`

**Comment by panzerdp** [comment]
It would be great to release a new version with the `browserify` and `package.json` main fixes  :+1:

**Comment by needim** [comment]
New release arrived. Can you give me a feedback?

**Comment by panzerdp** [comment]
Thanks @needim, it works well now with `2.3.5` version.
