### ISSUE TITLE
BUG: alerts not closeable under certain circumstances

### ISSUE THREAD

**Issue by r3wt** [needim/noty#265]
Getting reports from users that alert messages sometimes don't close. not sure what could be the cause. The only definite repro for the issue is if the code throws an exception then the box becomes uncloseable.

**Comment by r3wt** [comment]
Ok, i'm encountering this bug on multiple websites now. it occurs on occasion even when no exception occured and the only way to clear it is with `$.noty.closeAll()`

**Comment by jylyn** [comment]
I have found this happens when the close is called before the box has fully opened.  You can try adding a delay before closing or do it using the afterShow callback.  Unfortunately it still happens if the user clicks to close it before the opening animation finishes.

**Comment by dustinbolton** [comment]
Unable to close via click or timeout even several seconds after the animation has stopped.  Using with animate.css.

**Comment by livewire1407** [comment]
I find this issue when using animate.css and clicking on the window before the animation is finished. Do you have any plans to change ("fix" in my opinion) this?

**Comment by krtezech** [comment]
hmm I've just oppened #282 for this, cause it's huge basic bug and I am stunned that this has been not solved yet.

**Comment by r3wt** [comment]
Could overlay it with a transparent div and listen for animationend event to remove the overlay. That would prevent the click from modifying the Dom and invalidating the node.

Sent from my Windows Phone
________________________________

**Comment by krtezech** [comment]
Thanks for reply, I just made own script fixing issues. But that means even more issues in the future =(

**Comment by caribnow** [comment]
This problem occurs even on the noty website. So is the temporary solution not to use animate.css?
