### ISSUE TITLE
Issue with backdrop closure while showing a non-closable message

### ISSUE THREAD

**Issue by WaleedAly** [needim/noty#267]
If you have 2 noty messages as follows:

A) modal: true, killer: true, closeWith: [] //User can't close message A
B) modal: true, killer: true, closeWith: ["click", "backdrop"]

When message A is on display and message B is triggered, B will kill A but B will only be closable by "click". "backdrop" closing will not work.

When message B is triggered in absence of message A, it works fine.

**Comment by WaleedAly** [comment]
I have worked around this limitation by adding the following as a callback option of message A:

	callback:{
		onClose: function() { $(".noty_modal").on("click", function() { $.noty.closeAll(); }); }
	}

**Comment by needim** [comment]
in v3 modal option is not supported anymore.
