### ISSUE TITLE
Support custom ID, and then disallow duplicates (RFC)

### ISSUE THREAD

**Issue by DarrenCook** [needim/noty#270]
Currently Noty assigns a DOM id as a random(-ish) string. I wondered if there is a good reason a user could not specify their own ID? And, then if that ID is already in use, do nothing. The patch is to replace this line:

```
this.options.id = 'noty_' + (new Date().getTime() * Math.floor(Math.random() * 1000000));
```

With:

```
if(this.options.id){
  if($.noty.store[this.options.id])return;  //Already there, do nothing
}else{
  this.options.id = 'noty_' + (new Date().getTime() * Math.floor(Math.random() * 1000000));
}
```

This then gives a graceful solution to this kind of issue:
    http://stackoverflow.com/q/22712194/841830

(At least, my understanding of that question! In my case I have a help icon on screen, and I have that add a `type:"information"` Noty object. But if the user clicks the help icon three times, we end up with three boxes on screen! My current crude workaround is to use `killer:true`)

It can also allow doing this kind of thing:

```
$.noty.close("noty_myHelpBox");
```

without having to record the return object from the `noty()` calls, or worry about if the help icon has been clicked or not.

(My use case for that is in a web app: when the user clicks a link to go to a new page, I want to remove any information boxes, which probably only applied to the page they were looking at, but still leave any error or alert boxes on screen, to be sure they have seen and processed them.)

**Comment by aasiph** [comment]
Hi,
Is this feature added or no plans on this.
This is not working for me. It is showing duplicates even though i pass ID.

`var i = 0;
        //Noty.closeAll();
        for(var error in errorOBJ){
            i++;
            new Noty({
                text: errorOBJ[error],
                type: "error",
                container: "#noty-container",
                timeout: false,
                id: "noty_bar_" + i
            }).show();
        }`

Infact the max 5 notification is also not working with custom id passing.
