### ISSUE TITLE
How to maintain notification open on:hover

### ISSUE THREAD

**Issue by devmarwen** [needim/noty#272]
Is there a way to maintain the notification open when hovered over?

**Comment by tobigit** [comment]
+1

**Comment by siddharthbhagwan** [comment]
Could you please rephrase the issue? If dismiss is on click, you can hover over it without any issues. So I guess I'm missing something.

**Comment by tobigit** [comment]
A new feature would be nice where the noty should close automaticly and hold open when the user moves the mouse-cursor on it. This is helpful when large text is displayed and the user has not enough time to read it.

**Comment by yamilovs** [comment]
Yep, i also think, that it will be a great feature

**Comment by needim** [comment]
v2.4.0+ has that feature.
