### ISSUE TITLE
Alerts not displaying

### ISSUE THREAD

**Issue by njb-said** [needim/noty#273]
I am trying out noty in a small project of mine, I am using the pre-packaged js un-minified, I am using it like so:

``` js
    $.noty.defaults = {
        layout:'top',
        theme:'defaultTheme',
        type:'alert',
        text:'',
        dismissQueue:true,
        template:'<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',
        animation:{
            open: 'animated fadeInDownBig',
            close: 'animated flipOutX',
            easing:'swing',
            speed:500
        },
        timeout:false,
        force:false,
        modal:false,
        maxVisible:5,
        killer: false,
        closeWith:['click'],
        callback:{
            onShow:function () {
            },
            afterShow:function () {
            },
            onClose:function () {
            },
            afterClose:function () {
            },
            onCloseClick:function () {
            }
        },
        buttons:false
    };

    noty({text: 'Test'});
```

The alerts are not displaying, when I say that I mean they are not showing up, but are on the page. I have both jquery and the pre packaged library as I mentioned above. I also highlighted the display:none attribute causing all the issues.

I chose to use animate.css for the animations as I saw it was supported. I also have this, it is in the initial <head> tag

My best guess is the animations are not running, however there are no errors in the chrome debug console.

I hope someone can help me figure out why it isn't showing up. Apart from this issue I like this library :smile: :+1:

**Comment by siddharthbhagwan** [comment]
Works for me! I'm on OS X, Chrome v 44.
Can you make a gist or provide some more info?

**Comment by ImAjayS** [comment]
Faced the same issue. It didn't work with jQuery 2.x whereas it worked with jQuery 1.x for me.

**Comment by r3wt** [comment]
Works fine for me with jQuery 2.x

**Comment by Orajo** [comment]
I have the same issue, including class "i-am-new". Problem tested in newest FF and Chrome.

**Comment by skylee91** [comment]
Yes, I am facing this problem right now when using the animation.css class name. If I remove the animation options, it is working.

Not working:
```
function showWithAnimationName() {
  noty({
    layout: 'top',
    theme: 'defaultTheme', // or relax
    type: 'error', // success, error, warning, information, notification
    text: 'msg', // can be HTML or STRING

    //dismissQueue: true, // If you want to use queue feature set this true
    //force: false, // adds notification to the beginning of queue when set to true
    //maxVisible: 5, // you can set max visible notification count for dismissQueue true option,

    //template: '<div class="noty_message"><span class="noty_text"></span><div class="noty_close"></div></div>',

    timeout: false, // delay for closing event in milliseconds. Set false for sticky notifications
    animation: {
      open: "animated tada", // or Animate.css class names like: 'animated bounceInLeft'
      close: "animated tada", // or Animate.css class names like: 'animated bounceOutLeft'


      //NOTE: easing and speed has no effect when string class name is being used.
    },
    closeWith: ['click'], // ['click', 'button', 'hover', 'backdrop'] // backdrop click will close all notifications

    modal: false, // if true adds an overlay
    killer: false, // if true closes all notifications and shows itself

    //callback: {
    //    onShow: function () { },
    //    afterShow: function () { },
    //    onClose: function () { },
    //    afterClose: function () { },
    //    onCloseClick: function () { },
    //},

    buttons: false // an array of buttons, for creating confirmation dialogs. });
  });
}
```
jsFiddle: [https://jsfiddle.net/skylee91/6t10q47t](url)

**Comment by needim** [comment]
@skylee91 which operation system and browser?

**Comment by skylee91** [comment]
@needim Hi, I changed to version 2.3.11, now the noty can show now but on click cannot dismiss the noty.

**Comment by needim** [comment]
@skylee91 because you are using the same animation class as closing ("tada"). Try something different. (exit-out animations)

**Comment by skylee91** [comment]
@needim it is working now. Thanks ^^

**Comment by needim** [comment]
@skylee91 you are welcome 👍
