### ISSUE TITLE
JS / JQuery in noty "text"-attribute

### ISSUE THREAD

**Issue by BeSt1979** [needim/noty#274]
Hi there.

I am new to noty.
I try to insert a piece of html / js code into noty´s text-attribute. I.e. here a div with a "$.mCustomScrollbar".

When opening the page where noty is used and clicking a line which opens a noty with this mCustomScrollbar, everythin is very fine!

![01](https://cloud.githubusercontent.com/assets/5738613/8231576/d3835fe2-15c9-11e5-8ee2-7d706aca78a5.png)

Then I click another line which opens another noty (i have the killer-attribute set to true). The noty opens, but the mCustomScrollbar is not shown.

![02](https://cloud.githubusercontent.com/assets/5738613/8231577/d383d184-15c9-11e5-8005-9e560cddeabc.png)

When I now close the noty by clicking on it and then open the same noty again, the mCustomScrollbar is correctly shown.

![03](https://cloud.githubusercontent.com/assets/5738613/8231578/d38605f8-15c9-11e5-95d8-cce98e85d48e.png)

Please see three attached images for explanation.

Could you image why I see this behaviour?

Thank you and best regards from Germany
Benni

**Comment by siddharthbhagwan** [comment]
Could you present some code or a gist or a fiddle so it'll be easier to debug?
