### ISSUE TITLE
Noty Close and Killer not working if Browser Page not in focus

### ISSUE THREAD

**Issue by Pemtium** [needim/noty#276]
Intranet Application.
we are testing Noty first so we could obtain noty manager later.

For some reason if you open a page  Noty popup OK then you open a 2nd page Noty Popup show up. we use Killer:true and also use close all (just for the first noty.) Working Perfect

we use an iframe refresh periodically (autorefresh) that show up noty on windows.parent (work ok)
so basically Noty show up ok when you go to each pages. (no problem) if yuo stay on same page and close noty (clicking) the autorefresh later will popup noty (ok).
also if you stay on page and few Noty show up. at the next autorefresh the killer and close all work ok

So all is ok at that point.

but if page is not in focus Killer and CloseAll dont work.

**Comment by 11digitlabs** [comment]
Hey @Pemtium . Did you find a solution to the issue described? I'm facing the same issue, thanks

@needim do you have any suggestions? Thank you!

**Comment by TheRealCuran** [comment]
I have this issue as well. I seem also be able to reproduce it, when an AJAX request completes really fast (maybe under the show animation time?).

The function which shows this behaviour looks (effectively) like:
```javascript
function loadPage() {
	var oNoty = noty({
		text : 'loading data',
		theme		: 'bootstrapTheme',
		animation	: {
			open	: 'animated fadeInRightBig',
			close	: 'animated fadeOutUp',
		},
		layout		: 'topRightCustom',
		dismissQueue : true,
		timeout		: false,
		force		: false,
		maxVisible	: 5,
		type		: 'information',
		buttons		: false,
	});

	$.ajax({
		…,
		complete : function() { oNoty.close(); }
	});
}
```
Obviously this is a shortened version, but that is all the Noty interaction (including all options) there is. `$.ajax()` may show an error message with Noty, but that's a different one with a timeout set. [And when I use `window.setTimeout()` in addition to the normal timeout option, I can (almost always) guarantee, that the error is closed.]

**Comment by TheRealCuran** [comment]
> I seem also be able to reproduce it, when an AJAX request completes really fast (maybe under the show animation time?).

This is probably a different bug: after further testing I can reliably trigger this with an `$.ajax()` request, that opens a Noty in `beforeSend` and closes it on `complete`, when the `complete` callback which calls `close()` on the Noty object, is executed while the show animation is still in progress. My solution has been to use a close() wrapper, that calls `.trigger('click')`on the Noty. That works reliably.

**Comment by jkrassman** [comment]
**Quote** "my solution has been to use a close() wrapper, that calls .trigger('click')on the Noty."

Any chanses that someone could show some code for this to a newbeginner?

**Comment by TheRealCuran** [comment]
> Any chanses that someone could show some code for this to a newbeginner?
It's really trivial, nothing special happening, but instead of calling `Noty.close()` directly, I'm calling the following helper function:
```javascript
function(oNoty) {
	oNoty.close();
	// cope with aborted animations
	if(typeof(oNoty) === 'object' && 'closed' in oNoty &&
	  oNoty.closed === false && 'options' in oNoty &&
	  'id' in oNoty.options) {
		$('#' + oNoty.options.id).trigger('click');
	}
}
```
You can probably spare yourself the `.close()` call altogether, but oh well, it doesn't hurt. AFAICT this works because the handler for the click event in Noty is different from the pure `.close()` handler.
Please note, that you need to pass in the Noty object you want to close.

**Comment by jkrassman** [comment]
@TheRealCuran  - thanks, that solved all my problems!

You are the king :)

Regards, Joakim
