### ISSUE TITLE
"infinite" class won't allow to dismiss

### ISSUE THREAD

**Issue by jaminroe** [needim/noty#281]
If I use the _infinite_ class from animate.css, I can't make the notification go away. Just using default options right now. Is there a particular API option that I should use to get this to work? Or is it a bug? Thanks!

![screen shot 2015-07-14 at 5 20 00 pm](https://cloud.githubusercontent.com/assets/1559447/8685485/e79ce574-2a4c-11e5-88dc-e30135bc9095.png)

**Comment by needim** [comment]
When using infinite class, animationend event never fired. Because of that noty can't define itself as shown. :/
