### ISSUE TITLE
Click event before animation is done, causes closing bug

### ISSUE THREAD

**Issue by krtezech** [needim/noty#282]
If the user clicks on that noty notification, right before the animation of that noty is done, the click event for that noty is broken and cannot be closed by click event anymore, so it stays on the screen 4ever.

Thanks for Your attention.

**Comment by krtezech** [comment]
I've found that is caused only with using animate.css, otherwise it's okay.

**Comment by livewire1407** [comment]
Yes it is only with animation.css I also notice. I have had to rid my code of using animation.css due to this but would love to be able to utilize it
