### ISSUE TITLE
Confirm buttons only appear to work on second click

### ISSUE THREAD

**Issue by plcrewe** [needim/noty#287]
I've got an annoying little problem which appears to only exist when using Chrome (I've tested it in Edge, IE11 and Firefox and it looks to work fine in all of them).

I can also reproduce the issue when running the main site (http://ned.im/noty/#/about) in Chrome.

When clicking the 'Center - Confirm' option, sometimes I see the 'hand' cursor straight away and I'm able to click the [OK] or [Cancel] button first time with no issue, whereas sometimes I click the option, the hand cursor doesn't appear and I have to click the button twice - the first time to make the cursor appear and the second time to allow me to click the button.

When running on Ned.Im, the prompt usually always works the first time - it's the second or third times that it misbehaves.

Any ideas?

**Comment by siddharthbhagwan** [comment]
I can't seem to replicate the issue. I am on OS X,  v44.0.2403.130.

**Comment by plcrewe** [comment]
Thanks, I'm running Windows 10 myself, but I also noticed it occurring on W8.1.

**Comment by plcrewe** [comment]
I've just installed v2.3.7 and this is still an issue in Chrome.

To reproduce, select http://ned.im/noty/#/about, scroll down to 'Layouts & Demos' so that the words 'Layouts & Demos' appears right at the top of the visible screen area.  Under 'Center', click 'Confirm' - sometimes the [OK] and [Cancel] buttons have focus (and the 'hand' pointer), sometimes they don't (in which case, the buttons have to be clicked twice - the first time to gain focus, the second time to activate).

**Comment by plcrewe** [comment]
I've been attempting to work around this by adding the following callback -

        callback: {
            /* Set the focus to the [OK] button to prevent the focus being lost in Chrome and causing the user to have to double-click it
             * (the first time to set focus and the second time to actually click the [OK] button itself)
             * See https://forum.jquery.com/topic/modal-dialog-does-not-focus-correctly-when-show-option-is-set */
            afterShow: function() {
                console.log('afterShow');
                setTimeout(function() {
                    $('.noty_buttons').focus();
                }, 300);
            }
        },

However - and here's the weird bit - the console statement doesn't appear until after I've clicked my mouse on the Noty dialog itself.  Only then does it set focus to the [OK] button.

I've also tried using the onShow() callback, but once again it doesn't consistently work in Chrome.

**Comment by siddharthbhagwan** [comment]
Can you check this again with the latest release? Still unable to reproduce the issue even after trying @plcrewe 's method
