### ISSUE TITLE
Documentation is unclear how to use different layouts

### ISSUE THREAD

**Issue by macu** [needim/noty#288]
The documentation at http://ned.im/noty/ is unclear how to use the different layouts. I guessed the following should work:

``` javascript
noty({
    layout: 'topleft',
    text: 'Test'
});
```

But I get "Uncaught TypeError: Cannot read property 'options' of undefined" in the console, related to [this line](https://github.com/needim/noty/blob/master/js/noty/packaged/jquery.noty.packaged.js#L48): `this.options = $.extend({}, this.options, this.options.layout.options);`.

**Comment by zaguerinho** [comment]
Also stuck on this. Regards

**Comment by siddharthbhagwan** [comment]
Use camelCase to fix this. Change `topleft` to `topLeft`
