### ISSUE TITLE
using with modal error

### ISSUE THREAD

**Issue by vatoer** [needim/noty#291]
i have issue using demo example from source
noty-2.3.6/demo/usingWithModal.html

setting options
modal : true
will trigger error 

"Uncaught TypeError: Cannot read property 'animation' of undefined"

**Comment by siddharthbhagwan** [comment]
Seems to be working fine for me. More info? What Browser, its version, OS? I'm on OS X Chrome v44.

**Comment by rabbal** [comment]
I Have same problem , with IE and Chrome and firefox

**Comment by rabbal** [comment]
this issue is for new version 2.3.6 . My problem is solved with older 2.3.5 version

**Comment by vatoer** [comment]
noty version 2.3.6 , os Windows, chrome 44 
yes back to noty 2.3.5 is good

**Comment by antokara** [comment]
The problem is on https://github.com/needim/noty/blob/v2.3.6/js/noty/jquery.noty.js#L409
```
modal.prependTo($('body')).fadeIn(self.options.animation.fadeSpeed);
```

replace with

```
modal.prependTo($('body')).fadeIn(notification.options.animation.fadeSpeed);
```

not worth a pull request

**Comment by vatoer** [comment]
@antokara 
thanks, it works, just like ur suggestion
i think  issue number #294 have same solution with yours
now . i may close this issue right ?
