### ISSUE TITLE
buttons?

### ISSUE THREAD

**Issue by alvarotrigo** [needim/noty#298]
Documentation seems a bit poor. Many options have no comments at all. 

Right now I'm a bit lost with the option `buttons`.
[I don't manage to make it work](http://jsfiddle.net/eyxqpep1/) and the documentation is not of any help in this regard.

**Comment by needim** [comment]
From documentation;

We can set button objects with an array like above;
```javascript
noty({
	text: 'Do you want to continue?',
	buttons: [
		{addClass: 'btn btn-primary', text: 'Ok', onClick: function($noty) {

				// this = button element
				// $noty = $noty element

				$noty.close();
				noty({text: 'You clicked "Ok" button', type: 'success'});
			}
		},
		{addClass: 'btn btn-danger', text: 'Cancel', onClick: function($noty) {
				$noty.close();
				noty({text: 'You clicked "Cancel" button', type: 'error'});
			}
		}
	]
});
```

**Comment by alvarotrigo** [comment]
Yeah, I just saw it right after posting the question. My mistake.
