### ISSUE TITLE
noty modifies the parameter value removing options such as `theme`

### ISSUE THREAD

**Issue by alvarotrigo** [needim/noty#302]
I was getting mad for like half an hour thinking the problem was outside the plugin somewhere else. I was not expecting a plugin to modify my parameter.

Noty modifies the parameter passed to the function removing options from it.

[Reproduction online](http://jsfiddle.net/5t5sL9vz/)

- Click twice over the link
- The first time the theme will be set and you'll see the bootstrap theme
- The second time you'll see how the bootstrap theme got lost as well as the layout. 

Ideally you want to define the options only once for the whole application.

I saw [the following lines](https://github.com/needim/noty/blob/master/js/noty/jquery.noty.js#L35) int he plugin, but as there are no comments on them I can not guess why they got removed:

```javascript
delete options.layout;
delete options.theme;
```

It doesn't sound like a good approach to me. Parameter should be kept intact.

**Comment by JustMikey** [comment]
+1

**Comment by Klian** [comment]
Same issue here. Any update on this ?

**Comment by needim** [comment]
Sorry for the delay. Fixed in v2.3.8.
