### ISSUE TITLE
Noty 2.3.7 is not on NPM

### ISSUE THREAD

**Issue by 11digitlabs** [needim/noty#303]
Hey @needim and thank you for all this good work you've done!
I'm trying to update to the latest version 2.3.7 through npm in order to solve the problem with the modals, but the latest version is not in the repository
https://www.npmjs.com/package/noty

Could you please update it?

Thank you very much!

**Comment by needim** [comment]
Published now, sorry about that. thanks for reporting, cheers!

**Comment by 11digitlabs** [comment]
Thanks a lot!
