### ISSUE TITLE
Noty: Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by JamesMcFall** [needim/noty#305]
Hi there
When using the uncompressed version of Noty (I'm having to to debug another issue) I get the error:

```
Uncaught TypeError: Cannot read property 'options' of undefined
```

This is triggered by line 43 jquery.noty.js

```
this.options = $.extend({}, this.options, this.options.layout.options);
```

Further up **$.noty.layouts** is used to set the **this.options.layout** property... but **$.noty.layouts** is always empty.

* * *

I'm using an older version of jQuery, 1.7.1 but that wouldn't cause this error. I'm using Noty 2.3.7. Below are the options I'm using.

```
        n = noty({
            text: 'NOTY - a jquery notification library!',
            layout: 'topRight',
            timeout: 2000,
            theme: "relax",
            type: 'success',
            animation: {
                open: 'animated fadeInDown',
                close: 'animated fadeOutUp', 
                easing: 'swing', 
                speed: 1000
            }
        });
```

Any ideas?

**Comment by JamesMcFall** [comment]
This could be down to the fact that I'm using a really old version of jQuery and can't change that.

**Comment by ambischof** [comment]
I get this too and I'm using v2.1.4

**Comment by CreepGin** [comment]
Same error here. Also using 2.1.4

**Comment by CreepGin** [comment]
Fixed it. I'm using bower. So I had to use `noty/js/noty/packaged/jquery.noty.packaged.js` instead of `noty/js/noty/jquery.noty.js`

**Comment by gitdust** [comment]
@CreepGin yes , I'm useing requirejs ,use your way ,it works,thks!
