### ISSUE TITLE
easing and speed have no effect when using animate.css

### ISSUE THREAD

**Issue by stamminator** [needim/noty#309]
I love the animate.css support, but it appears that when an animate.css class is being used in the `open` or `close` properties that there's no point using `easing` or `speed`. This makes sense, but the documentation is unclear on that. In usingWithAnimate.css.html, here is what the animation property looks like:

    animation : {
          open  : 'animated bounceInLeft',
          close : 'animated bounceOutLeft',
          easing: 'swing',
          speed : 100
    }

Because `easing` and `speed` seem to have no effect when animate.css is being used, they should not both be used simultaneously. This would make the documentation much clearer.

**Comment by needim** [comment]
Added to the documentation page.
