### ISSUE TITLE
how to disable animation?

### ISSUE THREAD

**Issue by digggggggggg** [needim/noty#316]
I'm sorry if I'm being daft but I can't work out how to disable the animation.

I'd like the dialog to show without any transition (no animate.css effect and no jquery easing).

May I suggest being able to set animation to false or 'none'?

**Comment by vallovic** [comment]
Have you had any luck with that? Having some problems with animations, would like to disable them completely.

**Comment by needim** [comment]
usage will be like this;
```javascript
...
animation: {
  open: null,
  close: null
}
...
```

**Comment by octopusthu** [comment]
Is this working in v2.4.1? 

With 
animation: {open: null, close: null}

The noty does not appear at all.

**Comment by needim** [comment]
Looks like it's working http://jsfiddle.net/needim/uyrkjdtt/

Maybe it's related with theme or layout? Can you test on this fiddle?

**Comment by octopusthu** [comment]
Everything works fine in jsfiddle but not my project. 

The code snippets are as follows:
```javascript
$.extend(true, $.noty.defaults, {
    theme: 'relax',
    type: 'warning',
    layout: 'topCenter',
    animation: {open: null, close: null},
    closeWith: ['button']
});
var n = noty({ text: 'abc.', closeWith: null });
```
Cannot figure out why. I'm using *animation: { speed: 0 }* as a workaround.
