### ISSUE TITLE
`noty({text: "..."})` makes it easy to inadvertently create XSS

### ISSUE THREAD

**Issue by yilangmok-gusto** [needim/noty#318]
It's quite common to write something like `noty({ text:`Hello ${name}`})`. Unfortunately text is directly written into the DOM through $.html(...) instead of $.text(...), which exposes an XSS bug.

```
        setText: function(text) {
            if(!this.closed) {
                this.options.text = text;
                this.$bar.find('.noty_text').html(text);
            }
            return this;
        },
```

Suggestion is to change $.html(...) to $.text(...). If people want to display HTML, they should pass the HTML through a different property, e.g. `htmlUnsafe`.

**Comment by needim** [comment]
Information added to documentation page.

**Comment by thomaskonrad** [comment]
A note in the documentation page (which I couldn't even find) is just not enough to address this issue. Please make `.text(...)` the default. You can't assume that people will sanitize the input before they put it into a notification!

**Comment by thomaskonrad** [comment]
I mean, what if I *do* want to put user input in there?
