### ISSUE TITLE
onShow is rather beforeShow

### ISSUE THREAD

**Issue by ar2oor** [needim/noty#328]
Hello,

onShow calback is called before animation, so i can't do anything after noty is created but animation is not completed. For example i can't focus button in noty, or can't select text range in noty - must wait to animation is complete and use afterShow calback (is slows user experience). I think onShow should be called after show, but before animation and onShow could be replaced with beforeShow.

> > self.$bar.show();
> > // here we go with onShow, so i can do something with noty after it was created,
> > // but animation is not completed
> > if (self.options.callback.onShow) self.options.callback.onShow.apply(self);
> > self.$bar.addClass(self.options.animation.open)

What do you think?

Artur

**Comment by needim** [comment]
You are right.
