### ISSUE TITLE
fix Height for multi rows message 

### ISSUE THREAD

**Issue by efureev** [needim/noty#330]
file : `jquery.noty.js`
row: `137`: 
`self.$bar.css('height', self.$bar.innerHeight());`
change to 
`self.$bar.css('min-height', self.$bar.innerHeight());`

![2016-09-15_19-05-35](https://cloud.githubusercontent.com/assets/5524684/18552796/d3641ffc-7b7f-11e6-96e7-8ae71cbf8a5b.png)

**Comment by needim** [comment]
fixed in v2.3.10
