### ISSUE TITLE
Closing when executing ajax call..

### ISSUE THREAD

**Issue by jkrassman** [needim/noty#331]
Hi,

I read alot of this issue and I cant get this to work. Before I execute the ajax call, I show a noty. When the call is done, I am trying to close the first one - and show a new Noty. But the first one is impossible to close, I guess that the executingtime is faster then the animation of Noty?

```
n = noty({
                text        : "<span class='fa fa-spinner fa-spin'></span> Sending textmessage...wait....",
                type        : 'warning',
                dismissQueue: true,
                layout      : 'topCenter',
                closeWith   : ['click'],
                theme       : 'relax',
                maxVisible  : 1,
                killer      : false,
                animation   : {
                    open  : 'animated bounceInLeft',
                    close : 'animated bounceOutLeft',
                    easing: 'swing',
                    speed : 200
                }
            });
$.ajax({
           type: "POST",
           url: "ac_sendMess.php",
           data: $("#frmCommunicate").serialize(), // serializes the form's elements.
           async : true, 
           success: function(data)
           {    
             n.close();
             generate("success","Text was sent!");
           }
         });

```

Any suggestions?

**Comment by Surzhikov** [comment]
Hi.
Same problem. I think the reason is: noty animation is not finish, when ajax success.
So I found 2  solutions of this problem:

**1) bad solution - use setTimeout**
_Ex.:_
<pre>
pageLoadNoty = noty({
	text: "<i class=\"fa fa-spinner fa-pulse\"></i> <b>Page load</b>",
	theme: 'bootstrapTheme',
	layout: 'topCenter',
	type: 'information',
	dismissQueue: true,
	timeout: false,
	killer:true,
	animation: {
		open: 'animated flipInX',
		close: 'animated flipOutX',
		easing: 'swing',
		speed: 100
	}
});

$.get("page.html",function(data){
	$("#content").html(data);
	/* Set timeout 1000 to close noty */
	setTimeout(function(){
		pageLoadNoty.close();
	},1000);
});
</pre>

**2) good solution - bind the noty animation end:**
_Ex.:_
<pre>
pageLoadNoty = noty({
	text: "<i class=\"fa fa-spinner fa-pulse\"></i> <b>Page load</b>",
	theme: 'bootstrapTheme',
	layout: 'topCenter',
	type: 'information',
	dismissQueue: true,
	timeout: false,
	killer:true,
	animation: {
		open: 'animated flipInX',
		close: 'animated flipOutX',
		easing: 'swing',
		speed: 100
	}
});

$.get("page.html",function(data){
	$("#content").html(data);
	/* Close noty, when animation finish */
	$("#"+pageLoadNoty.options.id).parent("li").one('webkitAnimationEnd oanimationend msAnimationEnd animationend', function(){
		pageLoadNoty.close();
	})
});</pre>

**Comment by donnyv** [comment]
When the noty close method is called. Noty should queue that close internally. Then call it when the animation is done. This keeps the user from having to deal with it.

**Comment by needim** [comment]
@donnyv You are right. I will check this cases.
