### ISSUE TITLE
Margin between messages

### ISSUE THREAD

**Issue by blindpenguin** [needim/noty#333]
Hi,

i might be blind, but i'm searching for an option to separate the messages if i create them. Currently they seem to get added to one single element and are connected with each other.

With my current implementation the function is called like this, if multiple messages are available:

https://jsfiddle.net/han1npru/3/

As you can see, all messages are in one single element with a thin line between them. I need them separated. In my project i'm actually using the bootstrap theme. There the connected messages look just weird.

Thanks.

**Comment by Fishthedj** [comment]
Is CSS an option for you? If so, you can use something simple like this:
https://jsfiddle.net/han1npru/4/
Only be aware that the id will change if you use different location for your noty message.

**Comment by needim** [comment]
It's defaultTheme's behaviour. You can use another themes or create one.
