### ISSUE TITLE
Pushing new package to Nuget

### ISSUE THREAD

**Issue by cantsdmr** [needim/noty#334]
To the author(s) of this repo:
    Could you update Noty package at Nuget **from 2.3.5 to 2.3.8** ?   

Thank you in advance.

**Comment by rogercoulson** [comment]
Looks like the existing nuget package isn't quite right with the bootstrap dependency... or it's not listed as a dependency so if you use the existing package it will back down your bootstrap version by a couple years. :/

**Comment by needim** [comment]
I don't have the ownership of Nuget package. :/
