### ISSUE TITLE
TypeError: this.$bar.transition is not a function

### ISSUE THREAD

**Issue by twocore** [needim/noty#336]
Hello,

since i update `noty` to `2.3.11` i got the following error on initialization:

```javascript
TypeError: this.$bar.transition is not a function
```

With `2.3.10` this error doesn't appears.

**Edit:** Currently i use jQuery 2.2.4

**Comment by needim** [comment]
I guess it's related with semanticui theme. Do you have semanticui javascript's on the page?

Because transition function comes with semantic-ui.
see: http://semantic-ui.com/modules/transition.html

**Comment by twocore** [comment]
Hi needim,

i realized them 2 minutes ago after i switched the theme to `relax`. After i included the `transition` module, the error disappears but after clicking on the notification (to close them), i got the error `TypeError: this.$bar is null`. It's not dramatically :-)

I think i will use the relax theme ;-)

**Comment by needim** [comment]
Oh, ok :) Even so I should debug the semantic-ui theme.

**Comment by brunotourinho** [comment]
I found something weird working with semantic... looks like onClose event removes the alert from screen before fire the transition function from semantic.
