### ISSUE TITLE
Close button doesn't display.

### ISSUE THREAD

**Issue by ofry** [needim/noty#337]
I have packaged Noty version 2.3.11.
```
var notification = noty({
                        text: 'SomeText',
                        type: 'information',
                        theme: 'relax',
                        layout: 'bottomRight',
                        closeWith: ['button', 'click'],
                        timeout: 5000,
                        animation: {
                            open: {opacity: 'show'},
                            close: {opacity: 'hide'},
                            easing: 'swing',
                            speed: 1700 // opening & closing animation speed
                        }
                    });
```

But Close button doesn't display :(

`<div class="noty_close" style="position: absolute; top: 4px; right: 4px; width: 10px; height: 10px; background: transparent url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAQAAAAnOwc2AAAAxUlEQVR4AR3MPUoDURSA0e++uSkkOxC3IAOWNtaCIDaChfgXBMEZbQRByxCwk+BasgQRZLSYoLgDQbARxry8nyumPcVRKDfd0Aa8AsgDv1zp6pYd5jWOwhvebRTbzNNEw5BSsIpsj/kurQBnmk7sIFcCF5yyZPDRG6trQhujXYosaFoc+2f1MJ89uc76IND6F9BvlXUdpb6xwD2+4q3me3bysiHvtLYrUJto7PD/ve7LNHxSg/woN2kSz4txasBdhyiz3ugPGetTjm3XRokAAAAASUVORK5CYII=&quot;) repeat scroll 0% 0%; display: none; cursor: pointer;"></div>`

**Comment by needim** [comment]
Close button appears on hover when using relax theme. Did you try the hover state. It's theme's behaviour.
