### ISSUE TITLE
v2.3.11 breaks password windows

### ISSUE THREAD

**Issue by djdance** [needim/noty#338]
in new v2.3.11 can' enter a pass: it hides by timeout and by click on text edit field.

in previous version - all fine.

**Comment by needim** [comment]
Hi @djdance, can you provide a jsfiddle example? onShow callback behaviour changed with last release, maybe it's related.

> #328 beforeShow callback added (triggered before animation start). onShow is now triggered when noty is ready for dom manipulations

**Comment by djdance** [comment]
im not so familiar with jsfiddle, but try:

https://jsfiddle.net/jn6gn31p/3/
click on text field. No luck.

if set timeout, it also will disapeear itself, before it wasn't so

**Comment by djdance** [comment]
I mean, it can silently break old projects linked with pass... I understand what we can fix it in code, but what if do not know

**Comment by needim** [comment]
Oh, I understand the problem. In previous releases if the buttons are provided timeout and the closeWith options was overwritten. In v2.3.11 we aren't overwriting the options anymore for flexibility. (#244, #247)

You can fix the problem with; 
```
closeWith: false,
timeout: false

**Comment by djdance** [comment]
thanks
