### ISSUE TITLE
Repeated the opening and closing of the prompt box

### ISSUE THREAD

**Issue by zhangfu-git** [needim/noty#339]
In the moment you want to close the prompt box, change the local time problems

**Comment by needim** [comment]
I didn't understand. Can you be a little more descriptive please.

**Comment by zhangfu-git** [comment]
when the prompt box is closed, I modify the device's time. Then the prompt box has been repeatedly bombs

**Comment by needim** [comment]
I didn't get it. But why are you changing device's time? Is there a use case for this scenario?
