### ISSUE TITLE
Header style

### ISSUE THREAD

**Issue by stibay** [needim/noty#342]
Was trying to figgure out why I couldn't manage to get a header in bold and the message in normal style. 
Figgured out that I was testing it in the error case and this css was beeing set as default:
`this.$message.css({fontWeight: 'bold'});`

Maybe abit confusing that this css is only applied to error and overrides what's beeing set in the text?

**Comment by needim** [comment]
Yep, sorry about that. v3 released and js themes are deprecated now. All themes are uses css now.
