### ISSUE TITLE
Progress Bar doesn't show when killer is set to true

### ISSUE THREAD

**Issue by lsultani** [needim/noty#346]
Expected the progress bar to still be visible since it is killing the entire notification, the new notification would have its own progress bar. BTW, Super plug in! Thanks for taking the time to build.

**Comment by needim** [comment]
I will check that, thanks!

**Comment by needim** [comment]
Yeah, I found the bug. It will be fixed in next release.

**Comment by needim** [comment]
fixed in v3, thanks again.
