### ISSUE TITLE
Using `n.setType()` yields `Uncaught TypeError`

### ISSUE THREAD

**Issue by fjeddy** [needim/noty#349]
HELLo,

I can't seem to get `n.setType()` to work. The following code

```
n_count = noty( {
      layout: 'bottomLeft',
      timeout: false,
      template: "<div class='noty'>Hmm</div>",
      type: 'warning',
      force: true,
      text: 'Going for it..',
      theme: 'default'
} )

n_count.setType( 'success' )
n_count.setText( 'All good' )
```

gives the error `Uncaught TypeError: Cannot read property 'apply' of undefined`. When using `setText` alone its working perfectly, but `setType` appears to be broken.

**Comment by needim** [comment]
Hi @fjeddy which version are you using?

**Comment by fjeddy** [comment]
Hello @needim , using the latest release.

**Comment by needim** [comment]
- There is no theme named as default. 
- Your template must have at least .noty_text class for the text replacement API
