### ISSUE TITLE
why did you define styles in javascript rather than in css?

### ISSUE THREAD

**Issue by kostark** [needim/noty#350]
I have such a problem when i decided to use this plugin.
from my eyes, it's more convenient to override style when styles were defined in a css files.

**Comment by kostark** [comment]
from my eyes, it's more convenient to override style when styles were defined in a css files.

**Comment by needim** [comment]
Yeah, it can be thought of as a design mistake now. 

It was 5 years ago, I wanted to be modular and flexible. So themes and layouts can have their own js object/functions/callbacks and people do what they want with them.

I guess it was not as useful as I imagined at the time. :) 

By the way themes are not necessarily need a js object. You can pass a string to theme option and style with CSS. Currently there is no detailed documentation for that but you can find an example here; https://github.com/needim/noty/blob/master/demo/themeCss.html

Maybe it's time for v3. (and maybe I can get rid of the jquery)

**Comment by kostark** [comment]
I see, thanks a lot for your answer.
