### ISSUE TITLE
Center layout v3 is blurry

### ISSUE THREAD

**Issue by potech** [needim/noty#351]
Noticed when using the center layout the noty is blurry you can see it on the demo page as well.

**Comment by needim** [comment]
Oh, you are right. :/

I did a research and this bug is a little shitty I guess. I didn't find a proper solution. Tweaking with zoom up&scale down etc is not good. :/

For centering calc(-50% - .5px) is the best possible solution I guess. Half pixel kinda acceptable.

**Comment by needim** [comment]
fixed in v3.0.1

**Comment by usb248** [comment]
Still here...
![image](https://user-images.githubusercontent.com/7659927/80423883-028c7500-88e1-11ea-9707-bc05c7890dc2.png)
without `translate(calc(-50% - .5px), calc(-50% - .5px)) translateZ(0) scale(1, 1)`
![image](https://user-images.githubusercontent.com/7659927/80423930-16d07200-88e1-11ea-813b-d02dc97dacc6.png)

=> in last version (v3.2.0-beta) in last version FF on windows 10.
