### ISSUE TITLE
Modal property does not work

### ISSUE THREAD

**Issue by MaximStone** [needim/noty#352]
> **_Noty version_**: 3.0.1
> **_Browser_**: Chrome
> **_OS_**: Windows 10
----------
Hello, as I understand "modal" property hasn't been implemented yet. Or it is bug?

Thank you!

**Comment by needim** [comment]
@MaximStone Yes, not implemented yet. Will be implemented in next release.

**Comment by needim** [comment]
Impemented in v3.1.0-beta

**Comment by ingcvillegas** [comment]
I like to know if there cuould a posibility to use noty with an overlay for notify the user something like [procesing...] for a process that may take some time?
noty.show -> start ... end -> noty.hide
without the posibility for user to interact
