### ISSUE TITLE
Documentation link unaccessable

### ISSUE THREAD

**Issue by lostinroom** [needim/noty#355]
Hi,

I am unable to access http://ned.im/noty/
I got Gateway Timeout
Server error - server 199.27.76.133 is unreachable at this moment.
Please retry the request or contact your administrator.

It has happened since last week.
Please help.

**Comment by needim** [comment]
Yep, it was unreachable but currently looks like reachable.

Maybe it's related with; https://status.github.com/messages
> 18:31 EEST - GitHub Pages builds are temporarily paused for unscheduled maintenance. GitHub Pages sites remain available.

**Comment by needim** [comment]
Also, If it's still unreachable for you and looking for v3 documentation, you can check [wiki pages](https://github.com/needim/noty/wiki).
