### ISSUE TITLE
Please use babel-runtime in stead of babel-polyfill

### ISSUE THREAD

**Issue by pieter-v** [needim/noty#356]
> **_Noty version_**: 3.1.0-beta
> **_Browser_**: all
> **_OS_**: all
> **_jsFiddle link (if available)_**: n/a
----------
babel-poly fill only allows one instance.
Since our application is build by ember-cli, it already pulls in the babel-polyfill, which results in an error at runtime:
only one instance of babel-polyfill is allowed

I found this nice article, explaining how to use babel-runtime and why libraries should use the runtime approach in stead of the polyfill approach:
https://medium.com/@jcse/clearing-up-the-babel-6-ecosystem-c7678a314bf3

**Comment by needim** [comment]
Oh, sorry about that @pieter-v  :/ and thanks for the useful link.
I will replace the library in next release.

**Comment by needim** [comment]
I replaced with es6-promise in 3.1.0, can you test it?

**Comment by pieter-v** [comment]
works like a charm, thanks
