### ISSUE TITLE
What happened to the Noty size?

### ISSUE THREAD

**Issue by creage** [needim/noty#358]
> **_Noty version_**: 3.1.0-beta
> **_Browser_**: .....
> **_OS_**: .....
> **_jsFiddle link (if available)_**: .....
----------
Could somebody explain to me, how the alerting plugin could be bigger than a whole jQuery library, please?

![capture](https://cloud.githubusercontent.com/assets/910967/25379019/eab10226-29ab-11e7-9d75-0214ce84de2f.JPG)

**Comment by needim** [comment]
It's because of babel-polyfill and this will change after beta. (3.1.0-beta)

**Comment by needim** [comment]
Resolved with v3.1.0
