### ISSUE TITLE
Custom ID breaks MaxVisible

### ISSUE THREAD

**Issue by martwalter** [needim/noty#362]
> **_Noty version_**: 3.1.0
> **_Browser_**: Firefox
> **_OS_**: Windows 10
> **_jsFiddle link (if available)_**: CodePen: http://codepen.io/martinwalter/pen/qRNqBN
----------
Hey Guys,

got some weird behavior when setting an custom Id to the Noty and opening it again and again (more than 5 times).
It seems it ignores the setMaxVisible value. If I remove the Id attribute its working.

Check:  http://codepen.io/martinwalter/pen/qRNqBN

Dont know if this is a bug or if it "work as designed".

**Comment by needim** [comment]
Yeah, it's a bug and nice catch! 👍 

It shouldn't create more than one notification, because there should be only one instance with that ID.

Thanks! I will fix that for next release.

**Comment by needim** [comment]
With v3.2.0-beta,

Using the same ID now returns previous noty object. Feel free to reopen.
