### ISSUE TITLE
ie8 problem

### ISSUE THREAD

**Issue by a05151988** [needim/noty#364]
> **_Noty version_**: v3.1.0
> **_Browser_**: IE8.0
> **_OS_**: win7
> **_jsFiddle link (if available)_**: .....
----------
Hey Guys , 
I had an error meesage " 'Noty' is undefined" in ie8,
my code just like this : 
```
jQuery(function(){
    $('#recruit').click(function(){
        new Noty({
            type: 'information',
            layout: 'topRight',
            theme: 'semanticui',
            text: 'brabra',
            timeout: 5000,
            progressBar: true,
            closeWith: ['click', 'button'],
            animation: {
                open: 'noty_effects_open',
                close: 'noty_effects_close'
            },
        }).show()
    })
})
```
is this version support ie8 ?

**Comment by needim** [comment]
CSS animations are not supported in IE8 or IE9. But, you can use JavaScript animation libraries.
http://caniuse.com/#feat=css-animation
