### ISSUE TITLE
Site seem to be unreachable

### ISSUE THREAD

**Issue by AndreaLombardo** [needim/noty#365]
Hi, I'think your site seem to be unreachable. Is it possible, or is my fault?
I tryed http://ned.im/noty

**Comment by needim** [comment]
Sometimes I can't reach too. It's hosted by GitHub pages (with custom domain) and all statuses are seems ok. I'm not sure why this is happening. :/

**Comment by needim** [comment]
related #355

**Comment by needim** [comment]
I think I found the problem. There was a wrong A record in my domain. I removed and It should probably fix the issue.

**Comment by AndreaLombardo** [comment]
Awesome!
