### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by dritir** [needim/noty#366]
> **_Noty version_**:  3.1.0
> **_Browser_**: Chrome

I dont know if this is the expected behavior, when creating Notys via chrome console spamming:
`new Noty({text: 'testing?'}).show();`
Will show the next noty only after closing the first.
by doing this:
`new Noty({queue: random_text_here, text: 'testing?'}).show();`
Noty is shown at moment.

**Comment by needim** [comment]
Every queue has a default maxVisible option as 5, and the default queue name is global. Are you sure default queue's maxVisible option greater then 1?

**Comment by dritir** [comment]
Hmmm, If I go to http://ned.im/noty/layouts.html and send this
`new Noty({
    text: 'Some notification text',
    timeout: 1000,
    queue: 'global'
}).show();
in the console 5 times, each one waits the last to appear, does it happen to you too?
`

**Comment by needim** [comment]
No. Are you sure? Because timeout value is 1 second and because of that they are closing too fast. Can you try with higher values like 5000?

**Comment by dritir** [comment]
`https://codepen.io/anon/pen/pPLPma`

Ok, I can't find a cause, sometimes I reload and it works normally sometimes it does for the first batch of Notys then if send again it doesn't. I tried firefox and other computer chrome same thing, sometimes it works sometimes it doesnt.

The only consistent behaviour that I found is that when it is not working everytime i click outside the screen (and the timeout resets) when I click again it shows me the next noty, (now 2 are showing), if I repeat 3 are showing; When all the 3 timeout more 3 appear, as if the maximum queue is now at 3 and adding one more each time I click outside and in, until a maximum of 5.

That and the fact that if use `queue: Math.random().toString()` as an option it will work as I expect everytime.

**Comment by needim** [comment]
I'm really sorry but I didn't get the case. Can you make a screencapture?

**Comment by dritir** [comment]
Here it is.
[noty.zip](https://github.com/needim/noty/files/993168/noty.zip)

**Comment by needim** [comment]
Wow that's weird. I'm gonna dig this issue. For now it looks like related with visibility control and max visible options.

**Comment by dritir** [comment]
Yeah, its very weird and sometimes I reload the page and it works.

**Comment by beachespecially** [comment]
I'm having an issue which could be related, where when I create a notification on the console with 
```
var a = new Noty({'text': 'test'});
a.show();
```
the noty isn't displayed immediately but with a delay. It worked with v3.0.0
I'll try to make a screencapture.
Noty version: 3.1.0
Browser: Chrome, Firefox (newest)

**Comment by needim** [comment]
This should be fixed with latest release.
