### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by fensterteam** [needim/noty#373]
Noty ver: 3.1.0

![image](https://cloud.githubusercontent.com/assets/13169981/26529262/8966d9ee-43c5-11e7-9043-2703e9e54408.png)
` new Noty({
               type: 'success',
               layout: 'top',
               theme: 'metroui',
              text: 'Ваша заявка принята! Вскоре мы свяжемся с вами!',
               timeout: 5000,
               progressBar: true,
               closeWith: ['click', 'button'],
               animation: {
                 open: 'noty_effects_open',
                 close: 'noty_effects_close'
               },
               id: false,
               force: false,
               killer: false,
               queue: 'global',
               container: false,
               buttons: [],
               titleCount: {
                 conditions: []
               },
               modal: false
             }).show(); `

**Comment by needim** [comment]
Hi @fensterteam, I tried but its working. Are you calling this when dom is ready?

**Comment by fensterteam** [comment]
Fuck this! Yep i forgot about checking if dom is ready! Thx. Also moving this script to body element helps!
