### ISSUE TITLE
Feature Request: Noty Condition

### ISSUE THREAD

**Issue by bluej130** [needim/noty#375]
Could we have an option to show notifications even when the document is not visible/on focus? If this is already an option, I was unable to find it in the documentation under the [options page](http://ned.im/noty/options.html).

**Comment by needim** [comment]
Actually there is an option for that: **visibilityControl** but currently it's a little bit buggy.
More details are here: #357 

Currently I'm too busy but I think next week I can work on it.

For quick fix you can commentout or remove line 2830 (it will disable all visibility control feature)
https://github.com/needim/noty/blob/master/lib/noty.js#L2830

**Comment by needim** [comment]
Fixed in v3.1.1
