### ISSUE TITLE
Install noty in laravel 5.4

### ISSUE THREAD

**Issue by pedja260** [needim/noty#377]
> **_Noty version_**: ..... 
> **_Browser_**: .....
> **_OS_**: .....
> **_jsFiddle link (if available)_**: .....
----------
Please explain how to install Noty in the Laravel 5.4

**Comment by needim** [comment]
I'm not familiar with Laravel but I guess you have to follow this; https://laravel.com/docs/5.4/mix#working-with-scripts

**Comment by user5885** [comment]
@pedja260 
I think i got it working.
what I did:
`npm install noty --save`
in boostrap.js : 
`require('noty');`
in app.scss: 
`@import "node_modules/noty/src/noty.scss";`

**Comment by Dreambox13** [comment]
If I do it manually,
Like, adding the noty plugin manually,
Add the link and the script on the file.
`<link href="lib/noty.css" rel="stylesheet"></script>`
`<script src="lib/noty.js" type="text/javascript"></script>`

And after in bootstrap.js
`window.noty = require('noty');`

What I need to add in app.scss ??
