### ISSUE TITLE
Noty 3.1.0 with RequireJS: Noty is not a constructor

### ISSUE THREAD

**Issue by crystalfp** [needim/noty#378]
> **_Noty version_**: 3.1.0
> **_Browser_**: Crome Version 59.0.3071.86 (Official Build) (64-bit)
> **_OS_**: Win 7 64 bits
> **_jsFiddle link (if available)_**: No fiddle
----------

Using Require JS to load Noty. In the main js file I have:
```
requirejs.config({
	paths: {
		"jquery":       "libs/jquery-3.2.1.min",
		"jquery-ui":    "libs/jquery-ui.min",
		"noty":         "libs/noty.min",
                ....
		"helpers":      "js/helpers",
	},
```

Then in the helpers module:

```
define(["jquery", "noty", "jquery-ui"], function($, Noty) {

function errorNotify(message) {
	new Noty({
		text: message,
		layout: "center",
		modal: true,
		type: "error",
		closeWith: ["click", "backdrop"]
	}).show();
}
```
But if I call errorNotify("My message"); I receive the following error:
```
Uncaught TypeError: Noty is not a constructor
```
I tried `import` and `require` but the first is unrecognized and the second gives the same error.
Any idea?
Thanks!

**Comment by needim** [comment]
I tried and same result, weird. I'm using umd as a output format. I didn't get it.

**Comment by crystalfp** [comment]
The Noty from define is undefined. That's why it is not a constructor.

**Comment by crystalfp** [comment]
Here a minimal example reproducing the problem. 
First, rename bug.txt into bug.zip (zip is accepted for upload but if I drop it github says wrong extension. Bah...)
Unzip in a directory and open bug.html in Chrome or Firefox.
Open the js console.
Push the button.
Watch the error message in the console.

[bug.txt](https://github.com/needim/noty/files/1060606/bug.txt)

**Comment by doubleysinglem** [comment]
I have the same issue, when I involve noty.js in requriejs. Noty is not defined.

**Comment by lelelic** [comment]
Try to write `Noty` and not `noty` in path e define statement

**Comment by crystalfp** [comment]
Solved: if in the requirejs paths side I define "Noty": "noty.min" everything works.
I was thinking the string is arbitrary, but seems not.
Could you at least document this requirement?

**Comment by needim** [comment]
Wow thanks @crystalfp I should put that in documentation page.
