### ISSUE TITLE
Progress Bar is not hiding

### ISSUE THREAD

**Issue by Grinzzly** [needim/noty#380]
> **_Noty version_**: 3.1.0 
> **_Browser_**: Chrome, FireFox, Opera, Safari, IE9+
> **_OS_**: MacOS
> **_jsFiddle link (if available)_**: .....
----------
When progressBar set to 'false' it is just stop decrease but did not disappear fro, container.
Is there any possible way to hide it?

**Comment by needim** [comment]
Oppps! Nice bug, sorry :) I will fix that, thanks!

**Comment by needim** [comment]
Fixed in 3.1.1
