### ISSUE TITLE
Confirm dialog has ugly transparent background.

### ISSUE THREAD

**Issue by max-wen** [needim/noty#383]
> **_Noty version_**: V3.1.0 
> **_Browser_**: Google chrome 59
> **_OS_**: Mac OSX 10.11
> **_jsFiddle link (if available)_**: null
----------

![cc8ac8a8-2644-4f52-a328-972d49bffb2b](https://user-images.githubusercontent.com/2849142/27208753-1c85e5fe-527a-11e7-9f1c-bc5852172274.png)

**Comment by needim** [comment]
I think you forgot to include css files.
