### ISSUE TITLE
Theming and Customizing Web Push Notifications 

### ISSUE THREAD

**Issue by 16alexanders** [needim/noty#386]
How can I change the color, layout, etc. of the web push notifications. They are just appearing as normal Javascript Notification API notifications. How can I get them to be beautiful like some of the examples? 

I'm thinking this isn't even possible? And I would instead need to post the notification JSON to my website... and create a Noty notification there using some of the JSON fields....?

**Comment by needim** [comment]
You can't change web push notification's appearance. They are browser specific. 

But maybe you can create Noty notification in serviceworker.js. I didn't tried yet so I'm not sure.
