### ISSUE TITLE
Question: Custom container allows custom HTML?

### ISSUE THREAD

**Issue by jaminroe** [needim/noty#395]
With the custom container option, could we make notifications that look like so:
![image](https://user-images.githubusercontent.com/1559447/28377341-704f4fc6-6c7a-11e7-81df-7459468f9fc4.png)

I'm hoping the answer is yes. Thanks!

**Comment by needim** [comment]
You can do it with onTemplate callback. 

```javascript
new Noty({
    ...
    callbacks: {
        onTemplate: function() {
            this.barDom.innerHTML = '<div class="my-custom-template noty_body">' + this.options.text + '<div>';
            // Important: .noty_body class is required for setText API method.
        }
    }
    ...
}).show();
```

I can create a fiddle if you need one. Let me know.

**Comment by jaminroe** [comment]
@needim if you could do something simple that would be excellent. I would pass this info on to my developers. Really appreciate it. I'm a designer, so most of this is over my head haha!

**Comment by needim** [comment]
Here; https://jsfiddle.net/needim/jo2t9skf/

I simply created a new type called **reply**. Then I modified html structure in **onTemplate** callback & some styles with css.

**Comment by jaminroe** [comment]
Thank you!!

**Comment by mateuszlewko** [comment]
I know this may be a bit off-topic, but how can I use vue component in barDom.innerHTML?

**Comment by afifnandya** [comment]
@mateuszlewko in my current project that's not possible
