### ISSUE TITLE
Confirm Box Synchronization

### ISSUE THREAD

**Issue by musaddiq-pk** [needim/noty#396]
> **_Noty version_**: 2.2.7
> **_Browser_**: All
> **_OS_**: Window
> **_jsFiddle link (if available)_**: .....
----------
Hi All,
I started to use jquery noty and it's very easy to implement.
I want to use the confirm box. It's very easy to implement. My issue is that I want to use it like javascript confirm box where the execution of code below it, is  stopped until "Okay" button is pressed. But here the box is displayed and code below is also executed.

Any idea!
Thanks in advance.

**Comment by needim** [comment]
You can move your code block into button's click callback.
