### ISSUE TITLE
Delay of showing Noty

### ISSUE THREAD

**Issue by truecoders** [needim/noty#398]
Need to implement delay of showing Noty, but with building of Noty's DOM with page.
How do you think?
Now need to do:
`setTimeout('noty.show()', 5000);`
or other methods…
I think need to add 
`new Noty({
text: 'Hi!',
delay: 5000
});`
to show Noty after some time after building the page, but build Noty with page.

**Comment by needim** [comment]
Hi, It's the second issue about that delay option. It's not a hard work to implement but do we really need this? What is the usecase of this? Can you give me an example usecase?

**Comment by truecoders** [comment]
Hi!
The biggest need is in building Noty together with the page, and then to show.
For example, we need to display Noty in 5 seconds after loading of the page and with an event on the Noty's button from an external script.
Now we can't do it. When external script loaded with page we have no button with the necessary selector on the page yet. It will appear 5 seconds later.

**Comment by needim** [comment]
I didn't get it totally but I will implement that option in next release. For now you can use setTimeout.

**Comment by truecoders** [comment]
[Please check it](https://jsfiddle.net/mrjohn73rus/97gepy1L/25/)

**Comment by truecoders** [comment]
By the way, you can do it in function show()
For example:
`new Noty({text: 'Hi!'}).show(5000);`

**Comment by needim** [comment]
@truecoders your problem is event delegation. Read this for more information: https://learn.jquery.com/events/event-delegation/

**Comment by truecoders** [comment]
%) Its not about jquery)) You can't understand what I mean.
If you need delay of showing and you use setTimeout, you can't delegate event to noty from outside, or input code in body from external script.
Well, this question is closed. I'll do it myself.
