### ISSUE TITLE
Updating Text in NOTY Popup ?

### ISSUE THREAD

**Issue by MadTomT** [needim/noty#400]
> **_Noty version_**: 2.3.4
> **_Browser_**: CHROME
> **_OS_**: ALL
----------

Hi

I'm displaying a NOTY with a message in it. I'd like to update the message shown, so the noty shows live updates.

I've tried this and the noty has a text input field with 'TEST' shown, but it never updates to say HELLO.

```
var n = noty({ type: 'information', layout: 'center', text: "<input id='msg' name='msg' value='TEST' />", 
dismissQueue: true, theme: 'relax', modal: true, maxVisible: 1 })

$('#msg').val('HELLO')

```

Can this be done ?
Thanks

**Comment by needim** [comment]
Try to update value in **afterShow** callback.
