### ISSUE TITLE
Adding animation option breaks the plugin

### ISSUE THREAD

**Issue by ds-ed** [needim/noty#401]
> **_Noty version_**: 3.1.2 
> **_Browser_**: Firefox,IE,Chrome
> **_OS_**: Windows 7
> **_jsFiddle link (if available)_**: .....
----------

Adding the animation or the button customization to the options breaks the plugin.
I get the following error when I do it in Firefox.

`TypeError: can't assign to properties of (new String("noty_effects_open")): not an object`

**Comment by needim** [comment]
Can you give an example?

**Comment by moraya-re** [comment]
```javascript
jQuery.fn.animate = jQuery.Velocity.animate;

Noty.overrideDefaults({
    layout   : 'bottomLeft',
    theme    : 'mint',
    timeout: 1000,
    closeWith: ['click'],
    animation: {
        open: function (promise) {
            var n = this;
            Velocity(n.barDom, {
                left: 450,
                scaleY: 2
            }, {
                duration: 0
            });
            Velocity(n.barDom, {
                left: 0,
                scaleY: 1
            }, {
                easing: [ 8, 8 ],
                complete: function() {
                    promise(function(resolve) {
                        resolve();
                    })
                }
            });
        },
        close: function (promise) {
            var n = this;
            Velocity(n.barDom, {
                left: '+=-50'
            }, {
                easing: [ 8, 8, 2],
                duration: 350
            });
            Velocity(n.barDom, {
                left: 450,
                scaleY: .2,
                height: 0,
                margin: 0
            }, {
                easing: [ 8, 8 ],
                complete: function () {
                    promise(function(resolve) {
                        resolve();
                    })
                }
            });
        }
    }
});

```

**Comment by moraya-re** [comment]
@needim Example using Velocity.

**Comment by needim** [comment]
Velocity dont exposes itself as Velocity when jquery is available. Can you try with `$.Velocity`

An example from our documentation page;

https://github.com/needim/noty/blob/2e6e811b1d8043949b59ef50b599becf284312da/docs/_assets/docs.js#L3

**Comment by moraya-re** [comment]
@needim Thanks a lot, bro. I wasn't able to figure that out. Have a great time.

**Comment by needim** [comment]
@moraya-re You too!

**Comment by ds-ed** [comment]
Hi Needim,

Thanks for the quick response. Please find below the link for the fiddle. It is a simple initialization that I'm doing.

[https://jsfiddle.net/gL51bkb4/2/](url)

`new Noty({
    layout: 'top',
    progressBar: 'true',
    theme : 'relax',
    text : 'Test',
    type : 'Alert',
    animation: {
      open: {height: 'toggle'},
      close: {height: 'toggle'},
      easing: 'swing',
      speed: 500
      }
  });`

**Comment by needim** [comment]
@ds-ed with v3 Noty animations usage is changed. Please take a look at documentation:
http://ned.im/noty/#/animations
