### ISSUE TITLE
Adding buttons option breaks the plugin

### ISSUE THREAD

**Issue by ds-ed** [needim/noty#402]
> **_Noty version_**: 3.1.2
> **_Browser_**: Firefox,Chrome,IE
> **_OS_**: Windows 7
> **_jsFiddle link (if available)_**: .....
----------
I get the following message on Firefox.
`TypeError: Argument 1 of Node.appendChild is not an object. `

**Comment by needim** [comment]
Can you give an example?

**Comment by ds-ed** [comment]
Please refer the following fiddle. The fiddle is not producing an error message but also doesn't do anything.

https://jsfiddle.net/adf1fg48/2/

`new Noty({
    layout: 'top',
    progressBar: 'true',
    theme : 'relax',
    text : 'Test',
    type : 'Alert',
    buttons : [
		 { 	addClass: 'btn btn-primary', text: 'Close', onClick: function($noty){
					$noty.close();
		 	}
		 }
		]
    });`

**Comment by needim** [comment]
@ds-ed with v3 Noty buttons usage is changed. Please take a look at documentation: 
http://ned.im/noty/#/confirm

**Comment by ds-ed** [comment]
Thank you. I did not know there was a separate site for the latest version.

**Comment by needim** [comment]
@ds-ed Good point!
