### ISSUE TITLE
Notification does not disappear

### ISSUE THREAD

**Issue by florianlenz** [needim/noty#403]
> **_Noty version_**: 3.1.2
> **_Browser_**: Chrome
> **_OS_**: OSX
> **_jsFiddle link (if available)_**: 
----------

A notification does not disappear even though i configured it. See my configuration:

```js
let notification = new Noty({
     type: 'error',
     layout: 'topRight',
     text: "My message",
     animation: {
         open: 'animated bounceInRight',
         close: 'animated bounceOutRight'
     },
    timeout: 3000
});

notification.show();
```

**Comment by keviswang** [comment]
same problem.

**Comment by keviswang** [comment]
same problem.

**Comment by needim** [comment]
Did you have animate.css in context?

**Comment by siddharthbhagwan** [comment]
Works with animate.css for Noty v3.1.2 on OSX Chrome. [And doesn't work without animate.css]

**Comment by longlife** [comment]
me too
