### ISSUE TITLE
Typescript Issues

### ISSUE THREAD

**Issue by Lusito** [needim/noty#405]
> **_Noty version_**: 3.1.2
> **_Browser_**: Chrome
> **_OS_**: Win7
----------

Just tried using the typescript definitions, but got the following issues:
1. overrideDefaults is missing in the d.ts file.
2. Why is the d.ts wrapped in a declare-module ? This way I need to import it (even though it's available in global namespace anyway) and also, requirejs tries to download noty.js, which obviously fails, because it's not located with the other compiled typescript files.

@zackschuster could you shine some light on this? thanks.

**Comment by zackschuster** [comment]
apologies for the miss -- there's probably a few things in the api i haven't done. [i've popped up a PR to address this](https://github.com/needim/noty/pull/406).

for the declare module, i was working under two assumptions:

1. that if you were using typescript, you were using import statements (ms's recommendation, even for node-style requires with `const foo = import('foo')`)
2. that if you were installing this through npm you were more than likely using the default main file, which is a generic webpack build (or, default types should assume default configuration)

as memory serves, if i tried to use import/export in the types, tsc would throw an incompatible module type error. meanwhile, `declare module` worked almost perfectly, as long as i did `import * as Noty from 'noty'`, which is basically all i needed. 

as it happens, i'm also using webpack in the project i wrote these for, so writing them this way was also very convenient for me.

---

anyway, that's basically what was going through my head, i'm open to working out additions/alternatives -- you mentioned adding window support to the types, which i've never done before. would it be similar to the `declare var $: any` construct?

**Comment by needim** [comment]
Merged. What about second part of this issue :)

**Comment by ninthz** [comment]
Why I still can't import.
Do you need to update the package version?

**Comment by needim** [comment]
Oh, I didn't release it yet.

**Comment by Lusito** [comment]
I honestly have not used npm for typescript.. when I started with typescript it seemed like it was just a different way of getting the compiler. I guess I need to read up on new ways and come back when I'm wiser.

On the other hand, DefinitelyTyped d.ts files still work exactly like before. just copy the file into your repository and start using it. Maybe take a look at how the @types/jquery & similar typescript definitions are created?

**Comment by zackschuster** [comment]
npm's great, definitely recommend. makes it very easy to pull down code. you might also look at [yarn](https://yarnpkg.com/en/) if it all strikes a chord 😄 

anyway, yeah, copying `@types/jquery` seems a pretty reasonable (and obvious...) path. i'll work on a separate PR to update the types for the window use-case (haven't looked at prior art yet, don't have an estimate -- ideally today, but who knows). 

i'd like to work out how i'd reconcile with your AMD workflow, but i'd rather put off any guarantees until i get a better handle on what that means.

**Comment by zackschuster** [comment]
@Lusito got a new version of the types worked out. this one strips out the `declare module "noty"` in favor of a top-level `declare class Noty` + `declare namespace Noty` approach with a simple `export = Noty` for AMD.

if you wouldn't mind testing them out, [i've plopped them into a gist](https://gist.github.com/zackschuster/aa17ecf778759de311e3385722fa00c1) so you can copy/paste. the global stuff seems to work for me; it's the AMD stuff that i would need confirmation for.

@needim -- i was able to do this without altering my code, so if it works for Lusito then there's a very good chance there won't be a breaking change for other TS users.

**Comment by Lusito** [comment]
@zackschuster does not work with AMD (cannot find name 'Noty')

**Comment by Lusito** [comment]
@zackschuster, I've tried making your gist work:
replace the `export = Noty;` with this:
```
declare module 'noty' {
    export = Noty;
}
```
seems to work so far. Does it work for you as well?

**Comment by zackschuster** [comment]
works perfectly, thanks! i'd had the `declare module` form before, but dropped it because you said it had issues -- good to know it actually works fine with AMD.

i've [dropped another PR](https://github.com/needim/noty/pull/408) using your change. ideally this wraps things up, but who knows 😉
