### ISSUE TITLE
Only "Nest" theme works.

### ISSUE THREAD

**Issue by qroft** [needim/noty#407]
> **_Noty version_**: 3.1.2 
> **_Browser_**: Latest Chrome
> **_OS_**: Windows 10
> **_jsFiddle link (if available)_**: --
----------
Trying in a page created with OctoberCMS and that contains the Semantic UI framework.
----------

I just added both necessary files to my website and the Noty notifications appear.
Every option works great, apart of the themes.
The only theme that i can choose is "nest"
All the others make the notification appear in white

I saw with the latter 2.4. version somewhere that i could define a path, but can not find this anymore for the Noty 3.x version. 
Am i missing to include something on my source, apart of the noty.js and noty.css ?

**Comment by Ridermansb** [comment]
Same wih me

**Comment by needim** [comment]
It's weird. Do you see the colors while using nest theme?

**Comment by Ridermansb** [comment]
For me, even nest theme didn't work

**Comment by needim** [comment]
Is noty.css loaded?

**Comment by zanematthew** [comment]
Downloaded the latest, installed, and noticed only the `mint` theme works. Also, for what its worth, probably just needs better documentation on how to use the themes.

Awesome library btw.

**Comment by needim** [comment]
I created a jsfiddle https://jsfiddle.net/needim/956h36zs/ It looks like working. Are you loading the correct css file?
https://github.com/needim/noty/blob/master/lib/noty.css

**Comment by zanematthew** [comment]
Thanks, works as expected.

One thing I did notice, is that following the examples I had not set the `type` option.
