### ISSUE TITLE
visibilityChangeFlow() tries to add event listener for 'undefined' in unsupported browsers, crashing JS execution

### ISSUE THREAD

**Issue by cerlestes** [needim/noty#410]
> **_Noty version_**: 3.1.3
> **_Browser_**: any unsupported browser (tested in old MSIE)
----------

In `utils.js`, `visibilityChangeFlow()` executes the following code:
```
let visibilityChange
if (...) {
    ...
    visibilityChange = 'visibilitychange'
}
...
addListener(document, visibilityChange, onVisibilityChange)
```

This leaves visibilityChange `undefined` when none of the conditions matches, which leads to it being handed to the `addListener()` function, where an Error is thrown that will effectively stop execution of all following JS code, potentially making the whole website unusable.

Either initialize the variable to the W3C default (first condition), or ignore `undefined` in `addListener()`.

**Comment by needim** [comment]
Wow, nice! Mainly Noty doesn't support old browsers but I'm gonna accept PR tomorrow.

**Comment by cerlestes** [comment]
Yeah we figured. Sadly it's still not working; probably because you need that event and MSIE9 doesn't have it. But at least it won't crash the page anymore. We didn't check the code further, maybe you can solve it even better and stop execution earlier when the browser isn't supported. Thanks for your work.

**Comment by christopherjbaker** [comment]
I have run into this same issue (in my case, the test environment) and came to nearly the same change before finding this issue. Please merge and release this PR.
