### ISSUE TITLE
support for angular 4 directives in messages

### ISSUE THREAD

**Issue by khan8698** [needim/noty#418]
Hi!
Is there any chance to add support for angular 4 directives in the messages.

Currently i am using it with angular 4 and it is working great but now i need to add a directive for some custom behavior in message shown in notification. but as noty HTML is not included in **app-root** tag so angular is not able to do its magic there.

Previous approach

`message: 'You have a new session to start.',`

new approach (which i want to implement)

`message: 'You have a new session to start. <div Countdown [duration]="10">...</div> ',`

Thanks in advance.

**Comment by needim** [comment]
Hi @khan8698, I'm not familiar with Angular. Can you suggest any documentation for that? How can we implement this?

**Comment by khan8698** [comment]
Hi @needim angular is a front end framework for building application. But i think you would know that already.
We can implement this if we make it a component available for users to import in the code. i can help you for this. Official documentation is well written and easy to understand though it is a little difficult for a starter but it will get better by time.

**Comment by needim** [comment]
Ok, are you preparing a PR :)

**Comment by khan8698** [comment]
Currently i am not if i will get the time i will try to build it. :)
