### ISSUE TITLE
Use css to make animation just like the v2 default style

### ISSUE THREAD

**Issue by bradhuang9999** [needim/noty#426]
> **_Noty version_**: 3.14
> **_Browser_**: IE,Chrome,Firefox
> **_OS_**: Windows 7
> **_jsFiddle link (if available)_**: .....
----------
Is is possible to just use css to make animation just like the v2 default style?
And make it as an example of animation css?

**Comment by needim** [comment]
Yes, it is possible. 

https://ned.im/noty/#/animations?id=css-animations

**Comment by bradhuang9999** [comment]
I have seen this example, but the effect appears horizontally. 
The original one is vertical, and the speed is stable.
I simply want it to slide down like v2.

**Comment by needim** [comment]
You can write a custom animation for that. Currently, I’m mobile but I can
write one tomorrow if you can’t figure out.

**Comment by bradhuang9999** [comment]
I try to use the Animate.css
But it still looks different.
https://jsfiddle.net/gjjqm07v/3/

**Comment by bradhuang9999** [comment]
And I try to write the same example in v2, to compare the difference.
https://jsfiddle.net/xpedhho8/1/

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

I'm closing issues for a fresh start. Feel free to reopen this issue if you are still interested.

Thanks.
