### ISSUE TITLE
CSS styles aren't being applied

### ISSUE THREAD

**Issue by GildedHonour** [needim/noty#428]
Both noty.css and noty.min.js are loaded. Nonetheless, noty notifications are being shown in grey as if the noty.css file weren't loaded at all

![_2018-03-11_12-32-39](https://user-images.githubusercontent.com/2032888/37249758-8b69a3e4-2528-11e8-98b4-549a6d2e831f.png)
![_2018-03-11_12-32-12](https://user-images.githubusercontent.com/2032888/37249759-8c4e997c-2528-11e8-8d3c-b32b93248a13.png)

The grey area on the background is top menu. 

However, the notifications are grey too, no matter what type I'm using: error, warning, success ....

If this matters -- I'm using twitter bootsrap too

**Comment by needim** [comment]
Hi @GildedHonour, which version are you using? We separated theme styles in v3.2.0-beta.

**Comment by GildedHonour** [comment]
v3.2.0-beta

I'm not using any theme. Only 2 files: noty.css and noty.js.  do you I have to use a theme?

**Comment by needim** [comment]
You need at least 1 theme. The default theme is **mint**.

Sorry for the missing documentation. v3.2.0 is still in beta.

**Comment by GildedHonour** [comment]
installation:
```

<link href="lib/noty.css" rel="stylesheet">
<script src="lib/noty.js" type="text/javascript"></script>
```

a noty theme isn't mentioned. how to attach one manually?

**Comment by GildedHonour** [comment]
I've downloaded the theme "relax" and now I'm doing this:



 
  <link rel="stylesheet"  href="/css/bootstrap.min.css" /> 
   <link rel="stylesheet"  href="/css/noty_theme_relax.css" />
  <link rel="stylesheet"  href="/css/noty.css" />
 
No change at all

**Comment by needim** [comment]
Sorry for the missing documentation. v3.2.0 is still in beta.

You need to pass the theme name as a parameter.
```
new Noty({
    theme: 'relax',
    text: 'Some notification text'
}).show();
```

And if you don't wanna pass the parameter every time you can override the default parameter like this;

```
Noty.overrideDefaults({
    theme    : 'relax',
});
```

**Comment by GildedHonour** [comment]
I'm doing this:

    function showNotification(type, text) {
      new Noty({
        type: type, /*alert, information, error, warning, notification, success*/
        text: text,
        timeout: 3000,
        layout: "topRight",
        theme: "relax"
      }).show();
    };


and:


      showNotification("error", "fdsafdsfds");


The theme isn't getting applied.

**Comment by GildedHonour** [comment]
Solved, thx

**Comment by needim** [comment]
What was the problem?

**Comment by GildedHonour** [comment]
i don't know, when I called it via Chrome tools it didn't work, even after I've cache

**Comment by navotera** [comment]
i got this problem too... this missing doc is getting me crazy :D

**Comment by neverender24** [comment]
same problem here 3.2.0 themes doesnt applied, only transparent, although I know the css is loaded since I can adjust the position, I'm using laravel 5.6

**Comment by cloakedch** [comment]
Same here. Any fixes?

**Comment by burhan-kun** [comment]
Same here i installed only the 2 files .css/.js and i have no theme on my notifications its blank

**Comment by davidalejandroaguilar** [comment]
Same here, I don't see the notification, yet is in the DOM. Looks like styles are missing.

**Comment by NelGarbuzova** [comment]
Hi guys. I solved problem for **Webpack** build. You need to import styles in the top of entry JS file:
```
import 'noty/lib/noty.css';
import 'noty/lib/themes/mint.css';
```
And use webpack config to load this styles. Something like this:
```
module: {
		rules: [
		    {
		        test: /\.css$/,
		        use: [
			        { loader: "style-loader" }, // creates style nodes from JS strings
			        { loader: MiniCssExtractPlugin.loader },
		            { loader: "css-loader" }, // translates CSS into CommonJS
		        ]
		    }
		]
	}
```

**Comment by jatin222** [comment]
How to download themes?

**Comment by AlisaYang** [comment]
> Sorry for the missing documentation. v3.2.0 is still in beta.
> 
> You need to pass the theme name as a parameter.
> 
> ```
> new Noty({
>     theme: 'relax',
>     text: 'Some notification text'
> }).show();
> ```
> 
> And if you don't wanna pass the parameter every time you can override the default parameter like this;
> 
> ```
> Noty.overrideDefaults({
>     theme    : 'relax',
> });
> ```

Please update documentation, thank you.
