### ISSUE TITLE
Add an option to verride z-index value

### ISSUE THREAD

**Issue by maofree** [needim/noty#442]
Hi
can you add an option to override the z-index value like for "theme" or "type" without using css code?

thanks
bye

**Comment by needim** [comment]
Hi @maofree,
Why not overriding a CSS rule? Is there a special use case?

**Comment by maofree** [comment]
hi
just for convenience
some plugins has this option and I like it
it is something that is appreciated by everyone

thanks
bye

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

I'm closing issues for a fresh start. Feel free to reopen this issue if you are still interested.

Thanks.
