### ISSUE TITLE
Load CSS on Vue.js webpack projects

### ISSUE THREAD

**Issue by jonorozcoc** [needim/noty#444]
> **_Noty version_**: 3.2.0-beta
> **_Browser_**: Chrome 68.0.3440.106 (64 bits)
> **_OS_**: Windows 10 (64 bits)
> **_jsFiddle link (if available)_**: .....
----------

When I import Noty it just load Noty javascript library, I had to load css by myself importing them. Can css files be loaded automatically by Javascript Noty library?

**Comment by hmaesta** [comment]
You have some options. Choose the best for you.

#### main.js
```javascript
import 'noty/lib/noty.css';
import 'noty/lib/themes/sunset.css';
```

#### vue.config.js
```javascript
module.exports = {
    css: {
        loaderOptions: {
            sass: {
                data: '@import "~noty/lib/noty.css"; @import "~noty/lib/themes/sunset.css";'
            }
        }
    }
}
```

#### App.vue
```scss
<style lang="scss">
    import '~noty/lib/noty.css';
    import '~noty/lib/themes/sunset.css';
</style>
```

----

Ps: I am just guessing the path for Noty files, I do not use it on Vue. Please correct if wrong.

**Comment by jonorozcoc** [comment]
Yes, you're right. I'm using the main.js setup. The idea I have it's to avoid those imports and loaded just importing the Noty module. Is that bad practice?

**Comment by hmaesta** [comment]
I don't know if that is possible – and, if possible, I don't know if is a bad practice. I am new to Vue, sorry ☹️

**Comment by kud** [comment]
Indeed. With webpack, I had to add those lines:

```
import "noty/lib/noty.css"
import "noty/lib/themes/mint.css"
```

But it also means that you've got to add the theme you're using there. I added "mint" as it's the default one.

**Comment by NelGarbuzova** [comment]
Hi guys. I solved problem for **Webpack** build. You need to import styles in the top of entry JS file:
```
import 'noty/lib/noty.css';
import 'noty/lib/themes/mint.css';
```
And use webpack config to load this styles. Something like this:
```
module: {
		rules: [
		    {
		        test: /\.css$/,
		        use: [
			        { loader: "style-loader" }, // creates style nodes from JS strings
			        { loader: MiniCssExtractPlugin.loader },
		            { loader: "css-loader" }, // translates CSS into CommonJS
		        ]
		    }
		]
	}
```

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

I'm closing issues for a fresh start. Feel free to reopen this issue if you are still interested.

Thanks.
