### ISSUE TITLE
Noty and VS2017 asp.net core 2.1 LibMan

### ISSUE THREAD

**Issue by eugene-g13** [needim/noty#447]
> **_Noty version_**: v3.2.0-beta.
> **_Browser_**: any
> **_OS_**: windows
> **_jsFiddle link (if available)_**: 

Visual Studio 2017 .net core 2.1 now has LibMan (Library Manager). In my project I had noty installed via Bower and now I'm changing it to LibMan. This problem is when I'm installing noty via LibMan I have only 'noty.js' and 'noty.css' files. I can't choose 'themes' folder to add. So I had to get themes manually and add them to my project and not in noty installation folder. Can u add themes to LibMan?

PS: 
the same problem with bounce.js file.

**Comment by needim** [comment]
I think Libman is using CDNJS as default. 

related: #425 
For now, you can create a libman.json and choose a filesystem provider instead of CDN provider. https://github.com/aspnet/LibraryManager/wiki/libman.json-reference
