### ISSUE TITLE
noty animation not working when jsp page submitted

### ISSUE THREAD

**Issue by dsethu** [needim/noty#448]
> **_Noty version_**: 2.4.0..... 
> **_Browser_**: IE.....
> **_OS_**: Windows 10.....
> **_jsFiddle link (if available)_**: .....
----------
Hi @needim 
Form the java web application, JSP page is submitted using action/submit using java script function.
noty message is shown but neither the progressbar nor the animation is working.
Used progressbar.html (saved as jsp) from the demo download from noty. 
var act = "../../jsp/progressbar.jsp";  
  this.document.forms[0].action = act;
  this.document.forms[0].submit(); 

Kindly suggest as how this can be resolved.

Same jsp page when opened using java script function, noty animation works.
var features = "dialogHeight:40; dialogWidth:125; dialogLeft:500; 
  dialogTop:300; status:no;scroll:no";  
  var url = "../../jsp/progressbar.jsp";    
  var retVal = window.showModalDialog(url,"",features);

**Comment by dsethu** [comment]
Hi Needim, your suggestion on the issue will be very much appreciated.

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

I'm not familiar with that environment, so I can't provide you a solution sorry. :/
