### ISSUE TITLE
Multiple notifications stacks.

### ISSUE THREAD

**Issue by amatzen** [needim/noty#450]
**_Noty version_**: 3.2.0-beta
**_Browser_**: 69.0.3497.81 (Official Build) (64-bit)
**_OS_**: macOS Mojave 10.14
**_jsFiddle link_**: https://jsfiddle.net/matzen/g5p1q6xu/42/
----------

Notifications stacks (see attachment):
![2018-10-28 14 49 12](https://user-images.githubusercontent.com/10503999/47617611-ec6de080-dac0-11e8-8226-28d7740e6780.gif)

Thanks in advance :)

**Comment by SwiftlyDesign** [comment]
I have the same issue, Would be great if anyone knows how to fix this issue.

**Comment by SwiftlyDesign** [comment]
I have found the issue, 
Change from the nest theme to something like MetroUi

Nest seems to stack behind instead of underneath

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

Yes, it's the nest theme's feature. I think the documentation is missing. I will check.

**Comment by amatzen** [comment]
Oh okay, thank you :)
