### ISSUE TITLE
Is it possible to perform asynchronous operations?

### ISSUE THREAD

**Issue by samuelterra22** [needim/noty#452]
> **_Noty version_**: ..... 
> **_Browser_**: .....
> **_OS_**: .....
> **_jsFiddle link (if available)_**: .....
----------

Is it possible to perform asynchronous operations?

**Comment by needim** [comment]
Hi, I went to military service in Turkey and after that, I moved to another country. Sorry for the late response.

I'm closing issues for a fresh start. Feel free to reopen this issue if you are still interested.

Thanks.
