### ISSUE TITLE
the msg bar doesn't expand until mouse over

### ISSUE THREAD

**Issue by margarettam** [needim/noty#453]
> **_Noty version_**: Jquery plugin 2.2.0
> **_Browser_**: Chrome Version 71.0.3578.98
> **_OS_**: Mac Yosemite 10.10.5
> **_jsFiddle link (if available)_**: .....
----------
I am using Noty on a legacy jsp project, when the noty msg pop up. the msg bar shows as a line and doesn't expand until mouse hover. I suspect other css files causing this problem, however it is hard for me  to find which css file causing this problem because this project is very chaotic. css and js files are all over the place

**Comment by needim** [comment]
Hi, you are using Dec 10, 2013 release. Use the latest version.
