### ISSUE TITLE
Add icon to text

### ISSUE THREAD

**Issue by sonsonixon** [needim/noty#457]
I read that the text option accepts HTML but its not working. Is there any way I can add something like font-awesome icons to noty text?

**Comment by sonsonixon** [comment]
Oh.. the HTML is working. Its just the icons that now showing.

`text   : '<i className="fa fa-fw fa-times"></i> This is a sample notification',`

**Comment by phlegx** [comment]
CSS `class` and not `className`:

`<i class="fa fa-fw fa-times"></i>Hey! Something very important here...`
