### ISSUE TITLE
How can I make Noty not timeout and close when the mouse pointer is hovering over the Noty message area?

### ISSUE THREAD

**Issue by howardb3115** [needim/noty#459]
> **_Noty version_**: 2.0.3 
> **_Browser_**: Chrome, Firefox, MS IE. MS Edge, Safari, and other popular browsers
> **_OS_**: Windows, Apple OS, IOS, Android, and other popular OS's.
> **_jsFiddle link (if available)_**: N/A
----------
I'm displaying messages for my web-apps users with Noty.js where the the message automatically closes after 5 seconds or the user clicks on the close 'X', but I want to prevent the message from automatically closing when the user floats the mouse pointer over the Noty message area so they can have more time to read the message.

I don't need this to be a new Noty option 'switch'. It can just apply to all Noty messages that have a false timeout value.

Note, if the user moves the mouse pointer away from the Noty message area then the timeout can either resume or start over, if resuming isn't easy or possible.

I'm using Noty version 2.0.3, so if this functionality is available in a later version, please let me know. I did read the Noty.js documentation for the latest version, but didn't see this feature.

Finally, I read all of the StackOverflow.com question headers on the 13 pages found at the time I searched for Noty.js, but if I missed this then please point me to the applicable message.

Thank you.

**Comment by needim** [comment]
v3 has this feature if you use **timeout** parameter.

**Comment by howardb3115** [comment]
Thank you, I'll give v3 a try.
